defaults:
 - _self_
 - dataset_localization: neurospin
 #- dataset: cristobal/SC-sylv_right_HCP
 #- dataset: cristobal/SC-sylv_right_UKB
 - dataset: cristobal/CINGULATE_left_CCD
 - model: BetaVAE
 - trainer: trainer
 - loss: CrossEntropy
