# @package _global_
dataset_name: CINGULATE_left_HCP
data_dir: ${dataset_folder}/CCD/crops/2mm/CINGULATE./mask/Lskeleton.npy
subject_dir: ${dataset_folder}/CCD/crops/2mm/CINGULATE./mask/Lskeleton_subject.csv
in_shape: [1, 18, 41, 38]
subjects_to_remove: None
remove_subjects: False