# @package _global_
dataset_name: CINGULATE_right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/CINGULATE./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/CINGULATE./mask/Rskeleton_subject.csv
in_shape: [1, 16, 37, 37]
subjects_to_remove: None
remove_subjects: False