dataset_folder: /lustre/fswork/projects/rech/tgu/umy22uu/Runs/70_self-supervised_two-regions/Input
save_dir: /lustre/fswork/projects/rech/tgu/uik34os/Runs/01_betaVAE/Output/2025-11-10/SC-sylv_right_UKB_16-20-03_123/
kl: 2
embedding_size: 10
depth: 3
'n': 75
batch_size: 32
nb_epoch: 150
lr: 0.0002
weights:
- 1
- 2
dataset_name: SC-sylv_right_UKB
data_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton.npy
subject_dir: ${dataset_folder}/UkBioBank40/crops/2mm/S.C.-sylv./mask/Rskeleton_subject.csv
in_shape:
- 1
- 52
- 40
- 56
subjects_to_remove: None
remove_subjects: false
